Repository AbdelrahmanBadr22/C_DataStructure_G1, pull requests merged in 2022-11, with the labels that each got.

#13 Adding implementation of doubly linked list [MRefat, ABadr]
  DoublyLinkedList.c
  DoublyLinkedList.h
Labels: enhancement

#20 [@MRefat,@ABadr]
  DoublyLinkedList.c
Labels: enhancement

#25 Adding implementation of Priority queue
  priority_queue_config.h
  priority_queuee.c
  priority_queuee.h
Labels: enhancement

#31 Adding implementation of Linked Stack by Linked List & Test it [@Manar,@ABadr]
  LinkedStack_byLinkedList.c
  LinkedStack_byLinkedList.h
  Stack.c
  TestDataStructures.c
  TestDataStructures.h
  main.c
Labels: enhancement

#32 Solving bug at DoublyLinkedList_Test (@ABadr, @MRefat , @Manar)
  TestDataStructures.c
Labels: bug

#34 adding implementaion of LinkedQueue_byLinkedList and Test it[@Noura,@ABadr]
  LinkedQueue_byLinkedList.c
  LinkedQueue_byLinkedList.h
  TestDataStructures.c
  TestDataStructures.h
  main.c
Labels: enhancement

#39 resolving a bug found in function EXPECT_FALSE() @Badr @Mariam
  SonicTest.h
Labels: bug

#37 Adding Priority queue to README file (Mariam,Badr)
  README.md
  TestDataStructures.c
  TestDataStructures.h
  priority_queuee.c
  priority_queuee.h
Labels: documentation

#40 edit TestDataStructures.c [@Noura,@ABadr]
  TestDataStructures.c
Labels: enhancement

#33 adding queue implementation[@Noran,@ABadr]
  Queue.c
  Queue.h
  Queue_Config.h
Labels: enhancement
