Repository AbdelrahmanBadr22/C_DataStructure_G1, pull requests merged in 2023-03, with the labels that each got.

#70 Adding Implementation of Binary Search Tree [@G1]
  CPP/BST/BST.cpp
  CPP/BST/BST.h
  CPP/BinaryTree/BinaryTree.cpp
  CPP/BinaryTree/BinaryTree.h
  CPP/DataStructures
  CPP/main.cpp
Labels: enhancement

#77 Solving bug in BST delete function
  CPP/BST/BST.cpp
  CPP/main.cpp
Labels: bug

#79 Adding BST Unit Test[@MRefat , @@Manar]
  CPP/BST/BST.cpp
  CPP/BinaryTree/BinaryTree.cpp
  CPP/BinaryTree/BinaryTree.h
  CPP/DataStructures
  CPP/TestDataStructures.cpp
  CPP/TestDataStructures.h
  CPP/UnitTest/BST_Test.cpp
  CPP/UnitTest/BST_Test.h
  CPP/UnitTest/SonicTest.h
  CPP/Utils/Test.cpp
  CPP/Utils/Test.h
  CPP/main.cpp
Labels: bug

#78 Insertionsort
  CPP/SortingAlgrothims/InsertionSort.cpp
  CPP/SortingAlgrothims/Sort.cpp
Labels: New

#80 add ShellSort[@Noura,@Badr]
  CPP/SortingAlgrothims/Sort.cpp
Labels: enhancement

#84 Gragh[@Noran,@Badr]
  CPP/BinaryTree/BinaryTree.cpp
  CPP/BinaryTree/BinaryTree.h
  CPP/main.cpp
Labels: New

#85 Add Counting Sort Implementation[@Manar,@Badr]
  CPP/SortingAlgrothims/Sort.cpp
  CPP/SortingAlgrothims/Sort.h
  CPP/UnitTests/SortingAlgrothims_Test.cpp
  CPP/UnitTests/SortingAlgrothims_Test.h
  CPP/UnitTests/UnitTests.cpp
Labels: New

#87 Adding implementation of Dynamic array Data structure [Badr]
  CPP/DynamicArray/DynamicArray.cpp
  CPP/DynamicArray/DynamicArray.h
  CPP/UnitTests/DynamicArray_Test.cpp
  CPP/UnitTests/DynamicArray_Test.h
  CPP/UnitTests/UnitTests.cpp
  CPP/build.dir
Labels: New
